### ISSUE TITLE
What's "root_gid" for?

### ISSUE THREAD

**Issue by affinityDrops** [ccloli/e-hentai-db#1]
Is it used to indicate the gallery has a parent gallery of id `root_gid`?

**Comment by ccloli** [comment]
Yes, it points to the root level of it&#39;s parent galleries. It can be used to determine duplicated old galleries, and to query its torrents (uploaded torrents are saved under root gallery). 
---原始邮件---
发件人:&quot;affinityDrops&quot;<notifications@github.com&gt;
发送时间:2020年7月14日 星期二 下午9:19
收件人:&quot;ccloli/e-hentai-db&quot;<e-hentai-db@noreply.github.com&gt;
抄送:&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;
主题:[ccloli/e-hentai-db] What&#39;s &quot;root_gid&quot; for? (#1)



Is&nbsp;it&nbsp;used&nbsp;to&nbsp;indicate&nbsp;the&nbsp;gallery&nbsp;has&nbsp;a&nbsp;parent&nbsp;gallery&nbsp;of&nbsp;idroot_gid?

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;are&nbsp;subscribed&nbsp;to&nbsp;this&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by affinityDrops** [comment]
> (uploaded torrents are saved under root gallery).

do only root galleries have uploaded torrents, not the descendants?

**Comment by ccloli** [comment]
Maybe, as on torrent search page, the gallery of each torrents is the root gallery, also on gallery torrent page, the tracker id is the root gallery.

![image](https://user-images.githubusercontent.com/8115912/87808197-e23ed780-c88b-11ea-9ccb-63d859772bab.png)

**Comment by affinityDrops** [comment]
Thank you for your detailed explanation!

I have one more question besides. Why is `torrent-import` marked as *USE AT YOUR OWN RISK*? Does this put a lot of load on the eh server?

**Comment by ccloli** [comment]
Yes, this script will request ALL the gallery torrent pages of galleries that mark `root_gid` as `NULL`. The script will do the following things:

1. Get all the galleries that doesn't set `root_gid`
2. Request the torrent page
3. Get the id from that tracker announce URL, and save it to the `root_gid` field
4. If the torrent page has one or more torrents, save them to `torrent` table with `gid` field as `root_gid`

Since when you import the `gdata.json`, you've imported about 800K galleries, so this script will request at least 800K times to get these informations.

I made a release [here](https://github.com/ccloli/e-hentai-db/releases), which includes a copy of my server's database dump. Also someone requested me to give him a latest dump about 2 weeks ago, so I also made a patch [here](https://www25.zippyshare.com/v/nDiDM4kR/file.html). If you want to run the server and start with a latest data set, you can just import these SQLs without importing `gdata.json`.

**Comment by affinityDrops** [comment]
I see that the only way to identify `root_gid` is to request one by one since the official API does not tell you about the parent.

I think that it would be good to have a flag for "`root_gid` existence is not determined". Once you know whether `root_gid` really exists or not, you don't have to request again since the existence of `root_gid` remains constant. Next thing to do is to create a long-running task version of `torrent-sync` to avoid too much frequent request. I might make a PR for it, but it is not that urgent.

Speaking about the database dump, that someone is me. Thanks anyway 😁
